ALTER TABLE users
    ADD COLUMN level INT NOT NULL DEFAULT 1,
    ADD COLUMN experience INT NOT NULL DEFAULT 0,
    ADD COLUMN coins INT NOT NULL DEFAULT 0,
    ADD COLUMN games_played INT NOT NULL DEFAULT 0,
    ADD COLUMN games_won INT NOT NULL DEFAULT 0;

